export const ACTION_TYPES = {
  LOAD_LESSONS: 'lessons/LOAD_LESSONS',
  LOAD_USER: 'user/LOAD_USER',
  TOGGLE_BOOKED_LESSONS: 'lessons/TOGGLE_BOOKED_LESSONS',
  LOAD_EVENTS: 'events/LOAD_EVENTS',
  SET_LOADER: 'events/SET_LOADER',
  SET_SUCCESS_ADDED: 'events/SET_SUCCESS_ADDED',
  ADD_EVENT: 'events/ADD_EVENT',
  EDIT_EVENT: 'events/EDIT_EVENT',
  REMOVE_EVENT: 'events/REMOVE_EVENT',
  TOGGLE_BOOKED_EVENT: 'events/TOGGLE_BOOKED_EVENT'
}